# Generated by Django 4.0.5 on 2022-06-20 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_project_developers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('create_at', models.DateField(auto_now_add=True)),
                ('date_of_end', models.DateField()),
                ('status', models.CharField(choices=[('Нужно сделать', 'Нужно сделать'), ('В работе', 'В работе'), ('Сделано', 'Сделано'), ('Готово к тесту', 'Готово к тесту'), ('Тестирование', 'Тестирование'), ('На доработку', 'На доработку')], max_length=255)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.project')),
            ],
        ),
    ]
